### ISSUE TITLE
The latest ISO is not booting and saying VMLINUZ not found

### ISSUE THREAD

**Issue by shadowwalkersteam** [t2linux/archiso-t2#10]
archlinux-t2-2022.10.01-x86_64 - Release Onimai 
I made USB pen drive with the above ISO but its not booting instead saying VMLINUZ missing.

**Comment by NoaHimesaka1873** [comment]
I am aware of this issue. Sadly I'm currently in the middle of midterm exams so I'm very busy. Will be fixed when I have time to properly examine the root cause of this issue.

**Comment by Netetra** [comment]
I am using a Macbook pro (13inch 2019) and have the same problem.

**Comment by NoaHimesaka1873** [comment]
@shadowwalkersteam @Netetra Fixed with 2022.10.06 release. Closing as fixed.
