### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by bsekura** [t2linux/archiso-t2#11]
With the latest iso, I am getting black screen.

MacBook Pro 16" 2019

Boot starts, text briefly flashes, I can see kernel messages up to "uevents", then screen goes black, after a while keyboard touchbar lights up and screen remains black.

Any tips appreciated.

**Comment by NoaHimesaka1873** [comment]
> MacBook Pro 16" 2019

Is it `MacBookPro16,1` or `MacBookPro16,4`?

**Comment by bsekura** [comment]
It's MacBookPro 16,4

**Comment by NoaHimesaka1873** [comment]
@bsekura use iGPU. MBP16,4's Radeon Pro 5600M is unsupported. Also get more support from t2linux Discord.
Closing as WONTFIX
