### ISSUE TITLE
Is not an issue just want to get info before installing

### ISSUE THREAD

**Issue by ds47x** [t2linux/archiso-t2#13]
I have Apple MacBook Pro 16" Touch 2.3GHz 8-Core i9 / 64GB / 2TB SSD/ 5500M w 8GB / Late 2019 /

I want to know what is supported and what's not...specially power management, hybrid (amd and intel), Gaming experience, touch bar,...etc. 

Just want to know which is supported now and which is not (or will be).

If I annoyed anyone I'm sorry but need to know everything

**Comment by NoaHimesaka1873** [comment]
Power management: sucks, don't expect suspend to work
Hybrid: very experimental module exists, unstable at best
Gaming: okay if you can get your thermal under control
Touch bar: compatibility mode, same as bootcamp
Sound: works, but better use external DAC/AMP
also, these are already explained in t2linux wiki

**Comment by ds47x** [comment]
> Power management: sucks, don't expect suspend to work
> Hybrid: very experimental module exists, unstable at best
> Gaming: okay if you can get your thermal under control
> Touch bar: compatibility mode, same as bootcamp
> Sound: works, but better use external DAC/AMP
> also, these are already explained in t2linux wiki
> 
I see and in the wiki it said I can control the fan speed which give me the chance to control the thermal ...perfectiò 

Tnx for the help
