### ISSUE TITLE
The Wireless Card is dropping a lot of packets

### ISSUE THREAD

**Issue by Sprungles** [t2linux/archiso-t2#14]
Note on the *Bonus* section: We have access to the internet for sure, as stated (as I am writing this issue on a macbook pro 15,1 with Arch Linux), but as I was playing games, i noticed large amounts of stutter, which means packet loss. I then proceeded to use wireshark, and the current iteration of driver is dropping a large amount of packets. Again, it is usable to get onto the internet, but if you have any idea of why the broadcom chip is dropping so many packets, please let us know!

**Comment by NoaHimesaka1873** [comment]
Come to t2linux Discord for support.
