### ISSUE TITLE
Not able to boot and / or install macOS after installing arch.

### ISSUE THREAD

**Issue by meky1** [t2linux/archiso-t2#16]
After installing arch I tried to boot macOS but the laptop entered in reboot loop, booting any linux distro is ok but macOS not.

Already followed apple guide to reset the firmware, control + option + shift for 7 seconds + power button for 7 seconds. Also option + command + p + r but the laptop not booting macOS.

Local recovery not work and internet recovery load the first download then laptop restart to the same internet recovery screen.

I wiped the drive, opened the back cover and removed the battery cable but also didn’t help.

I created a bootable macOS usb but also the laptop not booting it and keep restarting if the usb connected.

I even booted arch iso and set hwclock thinking it will fix the problem but not.

Any help please?
The laptop is Macbook Pro 16 inc 2019 in very clean condition.
It was always up to date and had the latest software and firmware.

**Comment by NoaHimesaka1873** [comment]
Not related to Arch Linux.
