### ISSUE TITLE
touchbar and wifi broken for 2023.12.24-t2

### ISSUE THREAD

**Issue by schnell18** [t2linux/archiso-t2#17]
I followed the [t2 offical installation guide for ArchLinux][1] to install the
2023.12.24-t2 on my 2019 macbookpro with Intel i9-9880H, 32G memory, 1T NVME
drive and touch bar. When it was booted on the USB drive, the touchbar and wifi
worked as expected. They no longer work when the macbook is booted on the hard
drive. The touchbar is compleltely dark and doesn't respond to any touch. Error
messages from dmesg and journalctl indicate the `tiny-dfr` keeps crashing due
to segfault.

The dmesg log snippet:

    [Sat Jan 27 08:21:13 2024] tiny-dfr[513]: segfault at 0 ip 00007bf945c78edd sp 00007fff93f50eb8 error 4 in libc.so.6[7bf945b44000+15a000] likely on CPU 5 (core 5, socket 0)
    [Sat Jan 27 08:21:13 2024] Code: 00 00 66 2e 0f 1f 84 00 00 00 00 00 90 f3 0f 1e fa 89 f8 48 89 fa c5 f9 ef c0 25 ff 0f 00 00 3d e0 0f 00 00 0f 87 33 01 00 00 <c5> fd 74 0f c5 fd d7 c1 85 c0 74 57 f3 0f bc c0 c5 f8 77 c3 66 66

The journalctl log snippet:

    Jan 27 08:21:13 vulcan systemd-coredump[517]: Process 513 (tiny-dfr) of user 0 dumped core.
                                              Stack trace of thread 513:
                                              #0  0x00007bf945c78edd n/a (libc.so.6 + 0x15aedd)
                                              #1  0x00005df600d57605 n/a (tiny-dfr + 0xda605)
                                              #2  0x00005df600d3b2a5 n/a (tiny-dfr + 0xbe2a5)
                                              #3  0x00005df600d3c5eb n/a (tiny-dfr + 0xbf5eb)
                                              #4  0x00005df600d3be24 n/a (tiny-dfr + 0xbee24)
                                              #5  0x00005df600d58dc3 n/a (tiny-dfr + 0xdbdc3)
                                              #6  0x00005df600d4fb69 n/a (tiny-dfr + 0xd2b69)
                                              #7  0x00005df600fbff4b n/a (tiny-dfr + 0x342f4b)
                                              #8  0x00005df600d3e175 n/a (tiny-dfr + 0xc1175)
                                              #9  0x00007bf945b45cd0 n/a (libc.so.6 + 0x27cd0)
                                              #10 0x00007bf945b45d8a __libc_start_main (libc.so.6 + 0x27d8a)
                                              #11 0x00005df600d2cd35 n/a (tiny-dfr + 0xafd35)
                                              ELF object binary architecture: AMD x86-64
    Jan 27 08:21:13 vulcan systemd[1]: systemd-coredump@0-516-0.service: Deactivated successfully.
    Jan 27 08:21:13 vulcan systemd[1]: tiny-dfr.service: Main process exited, code=dumped, status=11/SEGV
    Jan 27 08:21:13 vulcan systemd[1]: tiny-dfr.service: Failed with result 'core-dump'.

The second issue is the wifi doesn't work either. Typing `iwctl station wlan0 connect <ssid>` returns immediately
rather than displaying prompt to enter password as when booted on USB drive.

Attached are the journalctl and dmesg logs.

[1]: https://wiki.t2linux.org/distributions/arch/installation/

[dmesg.log](https://github.com/t2linux/archiso-t2/files/14070511/dmesg.log)
[journalctl.log](https://github.com/t2linux/archiso-t2/files/14070513/journalctl.log)

**Comment by NoaHimesaka1873** [comment]
reboot to macOS and try booting into Linux again.
