### ISSUE TITLE
TouchBar broken on the installation because `tiny-dfr` keeps crashing

### ISSUE THREAD

**Issue by Hardwaregore** [t2linux/archiso-t2#18]
After installing Arch Linux with the guide on the t2 wiki, I found that the Touch Bar doesn't work on the final installation. `systemctl status` shows that `tiny-dfr` keeps crashing due to a set fault.

![IMG_1146](https://github.com/t2linux/archiso-t2/assets/88296644/888d7482-8df7-4487-8dcc-09fef7a38f88)

`journalctl` also gives no helpful information.

![IMG_1147](https://github.com/t2linux/archiso-t2/assets/88296644/bf3c11d3-0d18-45a6-9b87-26425dc5d471)

The Touch Bar worked on the installation ISO. When running the `tiny-dfr` executable directly, it just says Segmentation Fault. `tiny-dfr` doesn't work even when I compiled it directly from the [git repo](https://github.com/kekrby/tiny-dfr). I followed the installation instructions on the wiki word for word and it doesn't work. All the files for `tiny-dfr` on the installation ISO are present on the disk, but `tiny-dfr` works on the ISO while it crashes on the installation. How can I stop `tiny-dfr` from crashing?

**Comment by NoaHimesaka1873** [comment]
Not a right place for that issue.
Anyways, try rebooting into macOS and back into Linux again.
