### ISSUE TITLE
./runmefirst.sh is not executable

### ISSUE THREAD

**Issue by bcmedeiros** [t2linux/archiso-t2#2]
I couldn't find the reason my pacstrap was not installing linux-t2, until I found this file. but it's not executable by default, so I had to do a chmod +x

not a big deal, but you may want to fix that.

I'll also check later what am I missing here, since t2linux guide does not mention this step to add the local repo. is that something new (probably filling another issue since this is off topic in this one?)

**Comment by NoaHimesaka1873** [comment]
I thought people would read MOTD at startup. (It tells you to run the script to add the repo) Guess I was wrong. And gotta fix that permission.

**Comment by NoaHimesaka1873** [comment]
fixed in commit `6d4c023c595b1fa8df8762b3a2992839ccc7d866`

**Comment by bcmedeiros** [comment]
thanks!

I read it, but not entirely. I was focusing more on the guide, which doesn't mention that.
