### ISSUE TITLE
ISO fails to load

### ISSUE THREAD

**Issue by brad** [t2linux/archiso-t2#3]
Latest ISO (2022-02-01) is failing to load. MacBookPro16,1
Flashed to USB using dd on mac

![PXL_20220204_033803008 MP](https://user-images.githubusercontent.com/1614/152468445-f709981b-7143-4675-93ab-7a26df3c0fd0.jpg)

**Comment by NoaHimesaka1873** [comment]
Hmm... seems like I have to rebase to newer archiso releng base. Wait a day or two.
