### ISSUE TITLE
Bootefi script in archinstall patched for --no-variables

### ISSUE THREAD

**Issue by red-smeg** [t2linux/archiso-t2#7]
there has been a patch #1228 to the archinstall to fix problem #1226. Can you update & reissue the iso as that is where the code is contained for doing a guided install.

**Comment by red-smeg** [comment]
the iso needs archinstall 2.5.1 to work on a MBP 16,1. Is there anyway the iso could be updated to that ?

**Comment by NoaHimesaka1873** [comment]
Updated and I'm against using archinstall. Closed.
